insert into tb_plataforma (nome) values 
    ('GitHub'),
    ('GitLab'),
    ('Bitbucket'),
    ('Jenkins'),
    ('CircleCI'),
    ('Travis CI'),
    ('Azure DevOps'),
    ('TeamCity'),
    ('Bamboo'),
    ('CodePipeline'),
    ('AWS'),
    ('Azure'),
    ('Oracle Cloud'),
    ('IBM Cloud'),
    ('Heroku'),
    ('DigitalOcean'),
    ('Linode'),
    ('Vultr'),
    ('Cloudflare'),
    ('Docker Hub'),
    ('Kubernetes'),
    ('Terraform Cloud'),
    ('Ansible Tower'),
    ('Grafana'),
    ('Prometheus'),
    ('ElasticSearch'),
    ('Kibana'),
    ('Datadog'),
    ('New Relic'),
    ('Slack'),
    ('Discord'),
    ('Mattermost'),
    ('Zoom'),
    ('Webex'),
    ('Telegram Bot API'),
    ('Signal API'),
    ('Twilio'),
    ('Jira'),
    ('Confluence'),
    ('Trello'),
    ('Asana'),
    ('Monday.com'),
    ('Basecamp'),
    ('ClickUp'),
    ('Notion'),
    ('Airtable'),
    ('Wrike'),
    ('Google'),
    ('Dropbox'),
    ('Box'),
    ('Zoho'),
    ('OnlyOffice'),
    ('LibreOffice Online'),
    ('Adobe Sign'),
    ('DocuSign'),
    ('PDFfiller'),
    ('Power BI'),
    ('Tableau'),
    ('Looker'),
    ('Qlik Sense'),
    ('Metabase'),
    ('Superset'),
    ('Mixpanel'),
    ('Hotjar'),
    ('Salesforce'),
    ('HubSpot'),
    ('Pipedrive'),
    ('Odoo'),
    ('SAP'),
    ('Microsoft'),
    ('Zoho CRM'),
    ('Bling ERP'),
    ('Totvs Protheus'),
    ('Omie'),
    ('OpenAI'),
    ('ChatGPT API'),
    ('Anthropic Claude'),
    ('Facebook (Meta)'),
    ('WhatsApp Business API'),
    ('Instagram Graph API'),
    ('LinkedIn Marketing'),
    ('Twitter API (X)'),
    ('Apple App Store Connect');