insert into tb_plataforma (nome) values 
    ('GitHub'),
    ('GitLab'),
    ('Bitbucket'),
    ('Jenkins'),
    ('CircleCI'),
    ('Travis CI'),
    ('Azure DevOps'),
    ('TeamCity'),
    ('Bamboo'),
    ('CodePipeline'),
    ('AWS'),
    ('Google Cloud Platform'),
    ('Azure'),
    ('Oracle Cloud'),
    ('IBM Cloud'),
    ('Heroku'),
    ('DigitalOcean'),
    ('Linode'),
    ('Vultr'),
    ('Cloudflare'),
    ('Docker Hub'),
    ('Kubernetes'),
    ('Terraform Cloud'),
    ('Ansible Tower'),
    ('Grafana'),
    ('Prometheus'),
    ('ElasticSearch'),
    ('Kibana'),
    ('Datadog'),
    ('New Relic'),
    ('Slack'),
    ('Discord'),
    ('Mattermost'),
    ('Microsoft Teams'),
    ('Zoom'),
    ('Google Meet'),
    ('Webex'),
    ('Telegram Bot API'),
    ('Signal API'),
    ('Twilio'),
    ('Jira'),
    ('Confluence'),
    ('Trello'),
    ('Asana'),
    ('Monday.com'),
    ('Basecamp'),
    ('ClickUp'),
    ('Notion'),
    ('Airtable'),
    ('Wrike'),
    ('Google Workspace'),
    ('Microsoft 365'),
    ('Dropbox'),
    ('Box'),
    ('Zoho'),
    ('OnlyOffice'),
    ('LibreOffice Online'),
    ('Adobe Sign'),
    ('DocuSign'),
    ('PDFfiller'),
    ('Power BI'),
    ('Tableau'),
    ('Looker'),
    ('Qlik Sense'),
    ('Metabase'),
    ('Superset'),
    ('Google Analytics'),
    ('Google Data Studio'),
    ('Mixpanel'),
    ('Hotjar'),
    ('Salesforce'),
    ('HubSpot'),
    ('Pipedrive'),
    ('Odoo'),
    ('SAP'),
    ('Microsoft Dynamics'),
    ('Zoho CRM'),
    ('Bling ERP'),
    ('Totvs Protheus'),
    ('Omie'),
    ('OpenAI'),
    ('ChatGPT API'),
    ('Anthropic Claude'),
    ('Gemini (Google)'),
    ('Facebook (Meta)'),
    ('WhatsApp Business API'),
    ('Instagram Graph API'),
    ('LinkedIn Marketing'),
    ('Twitter API (X)'),
    ('Apple App Store Connect');