insert into tb_plataforma (nome, url, icone) values
  ('GitHub', 'github.com', 'https://logo.clearbit.com/github.com'),
  ('GitLab', 'gitlab.com', 'https://logo.clearbit.com/gitlab.com'),
  ('Bitbucket', 'bitbucket.org', 'https://logo.clearbit.com/bitbucket.org'),
  ('Jenkins', 'jenkins.io', 'https://logo.clearbit.com/jenkins.io'),
  ('CircleCI', 'circleci.com', 'https://logo.clearbit.com/circleci.com'),
  ('Travis CI', 'travis-ci.com', 'https://logo.clearbit.com/travis-ci.com'),
  ('Azure DevOps', 'dev.azure.com', 'https://logo.clearbit.com/dev.azure.com'),
  ('TeamCity', 'jetbrains.com', 'https://logo.clearbit.com/jetbrains.com'),
  ('Bamboo', 'atlassian.com', 'https://logo.clearbit.com/atlassian.com'),
  ('CodePipeline', 'aws.amazon.com', 'https://logo.clearbit.com/aws.amazon.com'),
  ('AWS', 'aws.amazon.com', 'https://logo.clearbit.com/aws.amazon.com'),
  ('Azure', 'azure.com', 'https://logo.clearbit.com/azure.com'),
  ('Oracle Cloud', 'oracle.com', 'https://logo.clearbit.com/oracle.com'),
  ('IBM Cloud', 'ibm.com', 'https://logo.clearbit.com/ibm.com'),
  ('Heroku', 'heroku.com', 'https://logo.clearbit.com/heroku.com'),
  ('DigitalOcean', 'digitalocean.com', 'https://logo.clearbit.com/digitalocean.com'),
  ('Linode', 'linode.com', 'https://logo.clearbit.com/linode.com'),
  ('Vultr', 'vultr.com', 'https://logo.clearbit.com/vultr.com'),
  ('Cloudflare', 'cloudflare.com', 'https://logo.clearbit.com/cloudflare.com'),
  ('Docker Hub', 'docker.com', 'https://logo.clearbit.com/docker.com'),
  ('Kubernetes', 'kubernetes.io', 'https://logo.clearbit.com/kubernetes.io'),
  ('Terraform Cloud', 'hashicorp.com', 'https://logo.clearbit.com/hashicorp.com'),
  ('Ansible Tower', 'redhat.com', 'https://logo.clearbit.com/redhat.com'),
  ('Grafana', 'grafana.com', 'https://logo.clearbit.com/grafana.com'),
  ('Prometheus', 'prometheus.io', 'https://logo.clearbit.com/prometheus.io'),
  ('ElasticSearch', 'elastic.co', 'https://logo.clearbit.com/elastic.co'),
  ('Kibana', 'elastic.co', 'https://logo.clearbit.com/elastic.co'),
  ('Datadog', 'datadoghq.com', 'https://logo.clearbit.com/datadoghq.com'),
  ('New Relic', 'newrelic.com', 'https://logo.clearbit.com/newrelic.com'),
  ('Slack', 'slack.com', 'https://logo.clearbit.com/slack.com'),
  ('Discord', 'discord.com', 'https://logo.clearbit.com/discord.com'),
  ('Mattermost', 'mattermost.com', 'https://logo.clearbit.com/mattermost.com'),
  ('Zoom', 'zoom.us', 'https://logo.clearbit.com/zoom.us'),
  ('Webex', 'webex.com', 'https://logo.clearbit.com/webex.com'),
  ('Telegram Bot API', 'telegram.org', 'https://logo.clearbit.com/telegram.org'),
  ('Signal API', 'signal.org', 'https://logo.clearbit.com/signal.org'),
  ('Twilio', 'twilio.com', 'https://logo.clearbit.com/twilio.com'),
  ('Jira', 'atlassian.com', 'https://logo.clearbit.com/atlassian.com'),
  ('Confluence', 'atlassian.com', 'https://logo.clearbit.com/atlassian.com'),
  ('Trello', 'trello.com', 'https://logo.clearbit.com/trello.com'),
  ('Asana', 'asana.com', 'https://logo.clearbit.com/asana.com'),
  ('Monday.com', 'monday.com', 'https://logo.clearbit.com/monday.com'),
  ('Basecamp', 'basecamp.com', 'https://logo.clearbit.com/basecamp.com'),
  ('ClickUp', 'clickup.com', 'https://logo.clearbit.com/clickup.com'),
  ('Notion', 'notion.so', 'https://logo.clearbit.com/notion.so'),
  ('Airtable', 'airtable.com', 'https://logo.clearbit.com/airtable.com'),
  ('Wrike', 'wrike.com', 'https://logo.clearbit.com/wrike.com'),
  ('Google', 'google.com', 'https://logo.clearbit.com/google.com'),
  ('Dropbox', 'dropbox.com', 'https://logo.clearbit.com/dropbox.com'),
  ('Box', 'box.com', 'https://logo.clearbit.com/box.com'),
  ('Zoho', 'zoho.com', 'https://logo.clearbit.com/zoho.com'),
  ('OnlyOffice', 'onlyoffice.com', 'https://logo.clearbit.com/onlyoffice.com'),
  ('LibreOffice Online', 'libreoffice.org', 'https://logo.clearbit.com/libreoffice.org'),
  ('Adobe Sign', 'adobe.com', 'https://logo.clearbit.com/adobe.com'),
  ('DocuSign', 'docusign.com', 'https://logo.clearbit.com/docusign.com'),
  ('PDFfiller', 'pdffiller.com', 'https://logo.clearbit.com/pdffiller.com'),
  ('Power BI', 'powerbi.microsoft.com', 'https://logo.clearbit.com/powerbi.microsoft.com'),
  ('Tableau', 'tableau.com', 'https://logo.clearbit.com/tableau.com'),
  ('Looker', 'looker.com', 'https://logo.clearbit.com/looker.com'),
  ('Qlik Sense', 'qlik.com', 'https://logo.clearbit.com/qlik.com'),
  ('Metabase', 'metabase.com', 'https://logo.clearbit.com/metabase.com'),
  ('Superset', 'superset.apache.org', 'https://logo.clearbit.com/apache.org'),
  ('Mixpanel', 'mixpanel.com', 'https://logo.clearbit.com/mixpanel.com'),
  ('Hotjar', 'hotjar.com', 'https://logo.clearbit.com/hotjar.com'),
  ('Salesforce', 'salesforce.com', 'https://logo.clearbit.com/salesforce.com'),
  ('HubSpot', 'hubspot.com', 'https://logo.clearbit.com/hubspot.com'),
  ('Pipedrive', 'pipedrive.com', 'https://logo.clearbit.com/pipedrive.com'),
  ('Odoo', 'odoo.com', 'https://logo.clearbit.com/odoo.com'),
  ('SAP', 'sap.com', 'https://logo.clearbit.com/sap.com'),
  ('Microsoft', 'microsoft.com', 'https://logo.clearbit.com/microsoft.com'),
  ('Zoho CRM', 'zoho.com', 'https://logo.clearbit.com/zoho.com'),
  ('Bling ERP', 'bling.com.br', 'https://logo.clearbit.com/bling.com.br'),
  ('Totvs Protheus', 'totvs.com.br', 'https://logo.clearbit.com/totvs.com.br'),
  ('Omie', 'omie.com.br', 'https://logo.clearbit.com/omie.com.br'),
  ('OpenAI', 'openai.com', 'https://logo.clearbit.com/openai.com'),
  ('ChatGPT API', 'openai.com', 'https://logo.clearbit.com/openai.com'),
  ('Anthropic Claude', 'anthropic.com', 'https://logo.clearbit.com/anthropic.com'),
  ('Facebook (Meta)', 'facebook.com', 'https://logo.clearbit.com/facebook.com'),
  ('WhatsApp Business API', 'whatsapp.com', 'https://logo.clearbit.com/whatsapp.com'),
  ('Instagram Graph API', 'instagram.com', 'https://logo.clearbit.com/instagram.com'),
  ('LinkedIn Marketing', 'linkedin.com', 'https://logo.clearbit.com/linkedin.com'),
  ('Twitter API (X)', 'twitter.com', 'https://logo.clearbit.com/twitter.com'),
  ('Apple App Store Connect', 'apple.com', 'https://logo.clearbit.com/apple.com');